server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micro?currentSchema=company-schema
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dll-auto: none
  liquibase:
    change-log: "classpath:db/changelog/2023/12/13-01-changelog.xml"
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: company-service-group
      topic:
        company-deleted-user: company-deleted-user-topic
    producer:
      group-id: company-service-group
      topic:
        company-deleted: company-deleted-topic


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

my:
  property:
    company: company-service


description: "company-service-description"