server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micro?currentSchema=company-schema
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dll-auto: none
  liquibase:
    change-log: "classpath:db/changelog/2023/11/01-01-changelog.xml"
    enabled: true

my:
  property:
    company: company-service


description: "company-service-description"